### PR TITLE
Week 2 task (latest version 2.1.0) 

### PR DESCRIPTION
**Pull request by monsterbat**
# Stage2 Week 2 Editor:蕭士晟(SC)

*home page*
- http://43.206.32.223:3000/

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Extend web page to full width without additional margins shown in below.

**Comment by monsterbat** [comment]
# Stage2 Week 2 revise
## Editor:蕭士晟(SC)

### Revise item : Extend web page to full width without additional margins by setting body margin:0.

*home page*
- http://43.206.32.223:3000/

**Comment by cwpeng** [comment]
Re-request review from reviewers section in the right side of this page, so that I can review for you.

**Comment by monsterbat** [comment]
Hi, Peng peng
Thanks for your remind, I just re-request the reviewer request, please help to check.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
